version: '3.9'

services:  
  nginx:  
    image: nginx:latest  
    container_name: nginx-container  
    ports:  
      - "80:80" # Bản đồ cổng 8090 của máy chủ đến cổng 80 của container  
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html # Tùy chọn: Gắn thư mục chứa các tệp HTML (nội dung web)  
    restart: always

volumes:
  nginx:
  html: