version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_TOKEN=root
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    #   - seccomp=mode=privileged
    restart: always
    volumes:
      - vault_data:/vault/data
    entrypoint: /bin/sh -c "vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=root"
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://0.0.0.0:8200/v1/sys/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  vault_data:
    driver: local
