version: '3.9'  

services:  
  admin-dashboad:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    container_name: react-app  
    restart: unless-stopped  
    ports:  
      - "80:80"  
    volumes:  
      - ./nginx/logs:/var/log/nginx  
    networks:  
      - app-network  

networks:  
  app-network:  
    driver: bridge