version: '3.9'  

services:  
  redis:  
    image: redis:latest  
    container_name: redis-server  
    command: [  
      "redis-server",  
      "--requirepass", "redis"
    ]  
    ports:  
      - "6379:6379"  
    volumes:  
      - ./redis-data:/data  
    networks:  
      - redis-network
    restart: always

volumes:  
  redis-data:  

networks:  
  redis-network: